spring:
  cloud:  # Eureka server URL
    gateway:
      mvc:
        routes:
          - id: identity-service
            uri: http://localhost:8091
            predicates:
              - Path=/api/v1/identity-service/**

          - id: customer-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/v1/customer-service/**

          - id: employee-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/employee-service/**

          - id: appointment-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/appointment-service/**

          - id: medicine-service
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/medicine-service/**

          - id: medical-prescription-service
            uri: http://localhost:8086
            predicates:
              - Path=/api/v1/medical-prescription-service/**

          - id: bill-service
            uri: http://localhost:8088
            predicates:
              - Path=/api/v1/bill-service/**

          - id: payment-service
            uri: http://localhost:8090
            predicates:
            - Path=/api/v1/payment-service/**

server:
  port: 8888
