spring:
  cloud:  # Eureka server URL
    gateway:
      mvc:
        routes:
          - id: identity-service
            uri: lb://IDENTITY-SERVICE
            predicates:
              - Path=/api/v1/identity-service/**

          - id: customer-service
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/api/v1/customer-service/**

          - id: employee-service
            uri: lb://EMPLOYEE-SERVICE
            predicates:
              - Path=/api/v1/employee-service/**

          - id: appointment-service
            uri: lb://APPOINTMENT-SERVICE
            predicates:
              - Path=/api/v1/appointment-service/**

          - id: medicine-service
            uri: lb://MEDICINE-SERVICE
            predicates:
              - Path=/api/v1/medicine-service/**

          - id: medical-prescription-service
            uri: lb://MEDICAL-PRESCRIPTION-SERVICE
            predicates:
              - Path=/api/v1/medical-prescription-service/**

          - id: bill-service
            uri: lb://BILL-SERVICE
            predicates:
              - Path=/api/v1/bill-service/**

          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
            - Path=/api/v1/payment-service/**

server:
  port: 8888
