spring:
  cloud:  # Eureka server URL
    gateway:
      mvc:
        routes:
          - id: identity-service
            uri: http://IDENTITY-SERVICE
            predicates:
              - Path=/api/v1/identity-service/**

          - id: customer-service
            uri: http://CUSTOMER-SERVICE
            predicates:
              - Path=/api/v1/customer-service/**

          - id: employee-service
            uri: http://EMPLOYEE-SERVICE
            predicates:
              - Path=/api/v1/employee-service/**

          - id: appointment-service
            uri: http://APPOINTMENT-SERVICE
            predicates:
              - Path=/api/v1/appointment-service/**

          - id: medicine-service
            uri: http://MEDICINE-SERVICE
            predicates:
              - Path=/api/v1/medicine-service/**

          - id: medical-prescription-service
            uri: http://MEDICAL-PRESCRIPTION-SERVICE
            predicates:
              - Path=/api/v1/medical-prescription-service/**

          - id: bill-service
            uri: http://BILL-SERVICE
            predicates:
              - Path=/api/v1/bill-service/**

          - id: payment-service
            uri: http://PAYMENT-SERVICE
            predicates:
            - Path=/api/v1/payment-service/**

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

server:
  port: 8888
