eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  activemq:
    broker-url: tcp://localhost:61616  # URL of the ActiveMQ broker for messaging
    user: admin  # ActiveMQ user
    password: admin  # ActiveMQ password

  datasource:
    url: jdbc:mysql://localhost:3307/identity_service
    username: root
    password: root

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false
    url: jdbc:mysql://localhost:3307/identity_service
    user: root
    password: root
    locations: classpath:db/migrations


server:
  port: 8091
  servlet:
    context-path: /api/v1/identity-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: xyrDapo8+iQ7k9vh/zGyUYIsOgI487NM9mAZbuh4fNJdzjVkWcEMeUR3/v0hEQGt