eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  activemq:
    broker-url: tcp://localhost:61616  # URL of the ActiveMQ broker for messaging
    user: admin  # ActiveMQ user
    password: admin  # ActiveMQ password

server:
  servlet:
    context-path: /api/v1/notification-service
  port: 8087
