eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  activemq:
    broker-url: tcp://localhost:61616  # URL of the ActiveMQ broker for messaging
    user: admin  # ActiveMQ user
    password: admin  # ActiveMQ password

server:
  port: 8089
  servlet:
    context-path: /api/v1/payment-service

payos:
  client-id: a958d849-7e46-4e8d-858e-4be20af0c605
  api-key: ef3949a0-0889-4729-a3e9-4d349a20b389
  checksum-key: e8b9b70c1d32e55e701bb393357b52096b17dabc340e25893d2bea9c3d5c7baa

service:
  bill-client:
    path: /api/v1/bill-service