eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  jpa:
    properties:
      hibernate:
        use_nationalized_character_data: true
        format_sql: true
        ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  # CONNECT SQL SERVER - HIBERNATE "application.properties"
  datasource:
    url: jdbc:mysql://localhost:3315/product_service
    username: root
    password: root

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8092
  servlet:
    context-path: /api/v1/product-service

service:
  upload-client:
    path: /api/v1/upload-service