eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:
  datasource:
    url: jdbc:mysql://localhost:3314/product_service
    username: root
    password: root

  jpa:
    show-sql: false  # Disable showing SQL in the logs
    hibernate:
      ddl-auto: update  # Automatically update the database schema on startup

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8092
  servlet:
    context-path: /api/v1/product-service

service:
  upload-client:
    path: /api/v1/upload-service