spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

cloudinary:
  cloud-name: dprkvtle0
  api-key: 545227972661364
  api-secret: CF9pY6z7criTROCZtPVPHh7lwbE

server:
  port: 8090
  servlet:
    context-path: /api/v1/upload-service